
# Add configuration values here, as shown below.


AWS_ACCESS_KEY_ID:
AWS_SECRET_ACCESS_KEY:
S3_BUCKET_NAME: avery-lane-dev



#trello
TRELLO_PUBLIC_KEY:
TRELLO_MEMBER_TOKEN:

TRELLO_BOARD_ID: 59e504af9ca33e97ab3b12d7
TRELLO_APPROVED_LIST_ID: 59e504af9ca33e97ab3b12da
TRELLO_REJECTED_LIST_ID: 5a25d75ddb4f8fbc72d45168
