
# Add configuration values here, as shown below.

AWS_ACCESS_KEY_ID: AKIAJPGUIIMGBFMZAMJA
AWS_SECRET_ACCESS_KEY: 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
S3_BUCKET_NAME: avery-lane


#trello
TRELLO_PUBLIC_KEY: 5b2374452c2e91e80ffce3c786aa4393
TRELLO_MEMBER_TOKEN: 119de6f4acfb742ed005712b80801cd5a70f7c9e0515bae8c6565b251639b5e3

TRELLO_BOARD_ID: 59e504af9ca33e97ab3b12d7
TRELLO_APPROVED_LIST_ID: 59e504af9ca33e97ab3b12da
